spring:
  application:
    name: PR_Reviewer

  datasource:
    url: jdbc:postgresql://localhost:5432/pr_reviewer
    username: postgres
    password: Postgre@54321

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
github:
  api:
    base-url: https://api.github.com