
server:
  port: 8080

spring:
  application:
    name: PR_Reviewer

  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver


    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true



  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
github:
  api:
    base-url: https://api.github.com
ai:
  openrouter:
    base-url: https://openrouter.ai/api/v1/chat/completions
    api-key: ${OPENROUTER_API_KEY:}
    model: openrouter/free